
common_words = [
    "and",
    "from",
    "it",
    "seen",
    "after",
    "with",
    "more",
    "our",
    "they",
    "any",
    "you",
    ">>>",
    "your",
    "was",
    "his",
    "been",
    "thanks",
    "now",
    "for",
    "the",
    "has",
    "would",
    "new" "with",
    "this",
    "that",
    'a','b','c','d','e','f','h','i','j','k','l','m','n','o','p',
    'q','r','s','t','u','v','w','x','y','z','A','B','C','B','E','F',
    'G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V',
    'W','X','Y','Z',
    'is','in','if','be','go','who','of','we','us','by','to','or'
]
